apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-two-svc
spec:
  selector:
    app: nginx-two
  ports:
  - port: 80
    targetPort: 80